import { useEffect } from "react";
import { motion } from "framer-motion";
import { setPageMeta } from "@/lib/seo";

export default function Terms() {
  useEffect(() => {
    setPageMeta({
      title: "Terms & Conditions — Pix Engineer",
      description: "Read the Terms & Conditions for using Pix Engineer's AI app builder, design-to-code converter, Pix Chat assistant, and prompt tools.",
      path: "/terms",
    });
  }, []);

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "WebPage",
    name: "Terms & Conditions — Pix Engineer",
    description: "Read the Terms & Conditions for using Pix Engineer's AI-powered app builder, design-to-code converter, and prompt engineering tools.",
    url: "https://pixengineer.com/terms",
    publisher: { "@type": "Organization", name: "Pix Engineer", url: "https://pixengineer.com" },
    dateModified: "2026-04-01",
  };

  return (
    <div className="min-h-screen pt-20 pb-16 gradient-bg">
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }} />
      <div className="container px-4 max-w-3xl mx-auto">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="glass rounded-2xl p-8">
          <h1 className="text-3xl font-bold mb-6">Terms & Conditions</h1>
          <div className="space-y-4 text-sm text-muted-foreground leading-relaxed">
            <p><strong className="text-foreground">Effective Date:</strong> April 2026</p>

            <h2 className="text-lg font-semibold text-foreground pt-2">1. Acceptance of Terms</h2>
            <p>By accessing or using Pix Engineer ("the Platform"), including the Build App, Design to Code, and Prompt Studio features, you agree to be bound by these Terms & Conditions. If you do not agree, please do not use our services.</p>

            <h2 className="text-lg font-semibold text-foreground pt-2">2. Service Description</h2>
            <p>Pix Engineer is an AI-powered platform offering four core services:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li><strong className="text-foreground">Build App:</strong> Generate full-stack web applications from natural language descriptions, including multi-page navigation, interactive components, and downloadable source code.</li>
              <li><strong className="text-foreground">Design to Code:</strong> Convert uploaded design images, wireframes, or sketches into production-ready HTML, CSS, and framework-specific code.</li>
              <li><strong className="text-foreground">Prompt Studio:</strong> Generate, improve, and analyze AI prompts for various use cases.</li>
              <li><strong className="text-foreground">Pix Chat:</strong> Chat with an advanced AI assistant for everyday tasks — explore ideas, write code, summarize, translate, and more, with optional web search and image inputs.</li>
            </ul>
            <p>Users receive free usage upon signup and may purchase credits to access premium AI models for higher-quality output.</p>

            <h2 className="text-lg font-semibold text-foreground pt-2">3. User Accounts</h2>
            <p>You must provide a valid email address and create an account to use our services. You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account.</p>

            <h2 className="text-lg font-semibold text-foreground pt-2">4. Credits & Usage</h2>
            <p>Credits are consumed per generation across all features — Build App, Design to Code, and Prompt Studio. Each feature has its own credit cost. Once used, credits cannot be refunded or transferred. Unused credits do not expire unless otherwise stated. The free tier provides unlimited usage with auto-selected AI models.</p>

            <h2 className="text-lg font-semibold text-foreground pt-2">5. Intellectual Property</h2>
            <p>You retain full ownership of the designs you upload, the prompts you create, and all code or content generated for you through the Platform. Pix Engineer retains the right to use anonymized, aggregated usage data to improve the service.</p>

            <h2 className="text-lg font-semibold text-foreground pt-2">6. Prohibited Use</h2>
            <p>You may not use the Platform for any illegal purpose, attempt to reverse-engineer our systems, generate malicious code, or abuse the service in any way that disrupts functionality for others.</p>

            <h2 className="text-lg font-semibold text-foreground pt-2">7. AI-Generated Content</h2>
            <p>All code and content generated by the Platform is produced by AI models and is provided "as is." While we strive for high quality, we do not guarantee that generated output will be free of errors, security vulnerabilities, or bugs. Users are responsible for reviewing and testing all generated code before deploying to production.</p>

            <h2 className="text-lg font-semibold text-foreground pt-2">8. Limitation of Liability</h2>
            <p>Pix Engineer is provided "as is" without warranties of any kind. We are not liable for any indirect, incidental, or consequential damages arising from use of the Platform, including damages from AI-generated code deployed in production environments.</p>

            <h2 className="text-lg font-semibold text-foreground pt-2">9. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Continued use of the Platform after changes constitutes acceptance of the updated terms.</p>

            <h2 className="text-lg font-semibold text-foreground pt-2">10. Contact</h2>
            <p>For questions about these terms, please reach out at <a href="mailto:support@pixengineer.com" className="text-primary hover:underline">support@pixengineer.com</a>.</p>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
